CREATE TABLE [dbo].[Address]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	[Line1] NVARCHAR(100) NOT NULL,
	[Line2] NVARCHAR(100) NULL,
	[City] NVARCHAR(200) NOT NULL,
	[StateProvince] NVARCHAR(200) NOT NULL,
	[ZipCode] NVARCHAR(25) NOT NULL,
	[DateCreated] DATETIME NOT NULL DEFAULT(GetUtcDate()),
	[DateLastModified] DATETIME NULL
)
